// Generated by https://quicktype.io

export interface ParsedDoc {
  // eslint-disable-next-line @typescript-eslint/naming-convention
  PassportRF?: PassportRF;
}

export interface PassportRF {
  birthDate: string;
  birthPlace: string;
  firstName: string;
  issueDate: string;
  issuer: string;
  issuerCode: string;
  lastName: string;
  middleName: string;
  identifier: string;
  sex: string;
}
